import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import "./globals.css";
import CallButton from "@/components/CallButton";




export const metadata: Metadata = {
  title: "ByteBeetle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen  overflow-x-hidden overflow-y-auto select-none flex flex-col justify-between">
        <Header />
        <CallButton />
        <div className="flex-1 overflow-y-auto">
          {children}

          <Footer />
        </div>
      </body>
    </html>
  );
}
